# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "clicktale"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Peterson"]
  s.date = "2012-05-18"
  s.email = "jeremy.g.peterson@gmail.com"
  s.executables = ["clicktaleize"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "app/controllers/clicktale_controller.rb",
     "app/views/clicktale/_bottom.html.erb",
     "app/views/clicktale/_top.html.erb",
     "bin/clicktaleize",
     "clicktale.gemspec",
     "config/clicktale.yml",
     "config/routes.rb",
     "init.rb",
     "install.rb",
     "lib/astrails/clicktale.rb",
     "lib/astrails/clicktale/controller.rb",
     "lib/astrails/clicktale/helper.rb",
     "spec/clicktale_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jeremygpeterson/clicktale"
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Make clicktale work with rails 3 projects"
  s.test_files = [
    "spec/clicktale_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 3.2.0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 3.2.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 3.2.0"])
  end
end
